apiVersion: v1
kind: ServiceAccount
metadata:
  name: multiclusterresource-controller-manager
  namespace: multiclusterresource-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multiclusterresource-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - alephat.io
  resources:
  - multiclusterresources
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - alephat.io
  resources:
  - multiclusterresources/status
  verbs:
  - get
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multiclusterresource-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multiclusterresource-manager-role
subjects:
- kind: ServiceAccount
  name: multiclusterresource-controller-manager
  namespace: multiclusterresource-system