# permissions for end users to view multiclusterresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: multiclusterresource
    app.kubernetes.io/managed-by: kustomize
  name: multiclusterresource-viewer-role
rules:
- apiGroups:
  - alephat.alephat.io
  resources:
  - multiclusterresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - alephat.alephat.io
  resources:
  - multiclusterresources/status
  verbs:
  - get
