# permissions for end users to edit multiclusterresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: multiclusterresource
    app.kubernetes.io/managed-by: kustomize
  name: multiclusterresource-editor-role
rules:
- apiGroups:
  - alephat.io
  resources:
  - multiclusterresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - alephat.io
  resources:
  - multiclusterresources/status
  verbs:
  - get
