apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: multiclusterresources.alephat.io
spec:
  group: alephat.io
  names:
    kind: MultiClusterResource
    listKind: MultiClusterResourceList
    plural: multiclusterresources
    singular: multiclusterresource
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              targetClusters:
                type: string
              placementPolicy:
                type: string
              replicasOverride:
                type: integer
              resourceManifest:
                type: object
                additionalProperties:
                  type: string
          status:
            type: object
            properties:
              targetClusters:
                type: array
                items:
                  type: string
    subresources:
      status: {}