on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: arc-runner-set
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_NAME: multiclusterresourcemanager
      TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.23
        uses: actions/setup-go@v5.1.0
        with:
          go-version: 1.23
      - name: Install build essential
        run: apt-get update && apt-get -y install build-essential
      - name: Login to Docker Hub
        run: echo ${{ env.DOCKER_PASSWORD }} | docker login -u ${{ env.DOCKER_USERNAME }} --password-stdin
      - name: Build
        run: make docker-build docker-push IMG="$DOCKER_USERNAME"/"$IMAGE_NAME":"$TAG"
